config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  get '/show', to: 'lists#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, :scope => :list_id
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list_id = params[:list_id]
    if @bookmark.save!
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save!
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def search
    raise
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.input :movie_id, collection: Movie.all %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg">
      <div class="container-fluid">
        <%= link_to 'Moviepedia', lists_path, class:"navbar-brand" %>
        <div>
          <%= link_to 'Top movies', list_path(1), style: 'margin-right: 3em'%>
          <%= link_to 'New list', new_list_path %>
        </div>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" list='liste-de-liste'>
          <datalist id="liste-de-liste">
            <% List.all.each do |i| %>
              <option value=<%= i.name %>>
            <% end %>
          </datalist>
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </nav>
    <main class='container'>
      <%= yield %>
    </main>
  </body>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script>
      const searchValue = document.querySelector('.form-control.me-2')
      const searchBtn = document.querySelector('.btn.btn-outline-success')
      let searchItem = searchValue.value

      if(searchValue){
        searchValue.addEventListener('keyup', (event)=> {
      searchItem = event.key === 'Backspace' ? searchItem.slice(0, -1) : searchItem + event.key;
      console.log(searchItem)
        })
      }

      if(searchBtn){
        searchBtn.addEventListener('click', () => {
          console.log('test');
          window.location.href = 'http://localhost:3000/show';
        })
      }
    </script>
</html>

app/views/lists/index.html.erb
<header>
  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <% @first_card = Movie.find(1) %>
      <div class="carousel-item active" style='background-image:url("<%= @first_card.poster_url %>")'>
        <h1><%= @first_card.title %></h1>
        <p><i class="fas fa-popcorn"></i><%= @first_card.rating %></p>
      </div>
      <% List.find(2).movies.each do |i| %>
        <div class="carousel-item" style='background-image:linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url("<%= i.poster_url %>")'>
          <h1><%= i.title %></h1>
          <p><i class="fas fa-popcorn"></i><%= i.rating %></p>
        </div>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</header>

<section class='container'>
  <% @favorite = List.find(2) %>
  <h3><%= link_to @favorite.name, list_path(@favorite) %></h3>
  <div class="row">
    <% List.find(2).movies.sample(3).each do |i| %>
        <div class='col-3' style='background-image:linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url("<%= i.poster_url %>")'>
          <h5><%= i.title %></h5>
          <p><i class="fas fa-popcorn"></i><%= i.rating %></p>
        </div>
      <% end %>
  </div>
</section>

<section class='container'>
  <% @favorite = List.find(3) %>
  <h3><%= link_to @favorite.name, list_path(@favorite) %></h3>
  <div class="row">
    <% List.find(2).movies.sample(3).each do |i| %>
        <div class='col-3' style='background-image:linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url("<%= i.poster_url %>")'>
          <h5><%= i.title %></h5>
          <p><i class="fas fa-popcorn"></i><%= i.rating %></p>
        </div>
      <% end %>
  </div>
</section>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<%= link_to 'add a movie',  new_list_bookmark_path(@list) %>

<section class='container'>
  <div class="row">
    <% @list.movies.each do |i| %>
        <div class='col-3 my-3' style='background-image:linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url("<%= i.poster_url %>")'>
          <h5><%= i.title %></h5>
          <p><i class="fas fa-popcorn"></i><%= i.rating %></p>
        </div>
      <% end %>
  </div>
</section>